### PR TITLE
Make the category field optional. It's gone from recent N26 CSVs.

### PR DESCRIPTION
**Pull request by ppetru**

### CODE REVIEW

**Comment by siddhantgoel** [comment]
Nice, thanks for the PR! Could you please add a quick test case as well?

**Comment by siddhantgoel** [comment]
Also, looks like there were some `flake8` errors which might need fixing.

**Comment by ppetru** [comment]
Should be all done, please have another look.

**Comment by siddhantgoel** [comment]
Thanks for the update! Two things:

1. there seem to still be some formatting errors. If you run `make lint` locally you should see everything that would fail also on the CI.
2. one side-effect I thought of this morning is that initializing the importer inside `config.py` would now work for some files and not for some others (for the ones before N26 dropped the `category` field). Can we also make the `category` field optional? One option I could think of is adding an `OPTIONAL_FIELDS` dictionary with the same structure as `HEADER_FIELDS`, and inside `is_valid_header` we could make the first check with only the output of `header_values_for`, and if that fails then remove the fields inside `OPTIONAL_FIELDS` and check again. The nice thing is that `extract` does not depend on this header so that should remain unaffected.

**Comment by ppetru** [comment]
PTAL:

1. Fixed the formatting errors, hopefully for good this time. :)

2. Thanks for the suggestion. I made the concept of optional fields general as suggested, though I had to take a different approach (the use of OrderedDicts would have made joining two of the complicated unless keeping all headers in both). However, I don't think I understand your concern about the importer now working for some files and not for others -- is_valid_header already works as you describe. What am I missing?

**Comment by siddhantgoel** [comment]
1. Awesome, thanks! Looks like `pytest` is failing for 3.5 but I'm happy to drop support for 3.5 after merging this MR, so that would not be a blocker from my side.
2. My concern is about the historical CSV files. The importer will work for the newer files but for the older ones (which don't have the `category` column) we'll raise an exception. This is also evident because this change modifies the existing test cases (adding the `include_optional` parameter). Ideally we shouldn't have to do this because the behavior should be backwards compatible.

**Comment by ppetru** [comment]
Thank you, PTAL:

1) This should be fixed now, let's see if it actually works on py3.5

2) I'm sorry, but I still don't follow the concern. is_valid_header() doesn't keep state and tries with and, only if needed, without the optional fields. The same class instance should therefore work with both newer and older files. Point taken about modifying existing test cases, so I cleaned that up.

**Comment by siddhantgoel** [comment]
Awesome, all concerns resolved. I'll merge this PR and drop support for 3.5. It's EOL anyway so I don't think we need to support it further.

Thanks for your PR!

**Comment by siddhantgoel** [comment]
Just published v0.5.0 which contains this fix.

**Pull request merged**
